### ISSUE TITLE
Why does it show its a Virus?

### ISSUE THREAD

**Issue by randomluisaa** [Hazuki-san/OsuBuddy-reversed#10]
https://www.virustotal.com/gui/file/189b317aa3992bce00d3e021b60b34211e96f7f6db5ff584956c01b2b753d903/detection

in the behavior tab in zenbox it also shows thats trying to connect to the internet

i dont really know what that means but i'm sure its nothing good

**Comment by Hazuki-san** [comment]
before you judge things, you can look into source code and understand what it does. I did **NOT** code this program and only provide the fixed source to make it able to compile. This has nothing to do with me.

**Comment by randomluisaa** [comment]
i judged nobody or anything, as i said idk that shit. Ofc it has something to do with you if you upload something without checking it yourself

**Comment by Hazuki-san** [comment]
Sorry about that, but yes. I can assure you this has no virus/malware inside.

The code were "encrypted/obfuscated" before and antivirus usually get confused between "real" virus and "encrypted/obfuscated" programs because usually virus or malware will encrypt/obfuscate itself to prevent the source code of the software being stolen.

**Comment by Hazuki-san** [comment]
I did check everything before publishing, you can see that I tend to improve a few things in those commits.

**Comment by Hazuki-san** [comment]
You can also see that the VirusTotal were reported as "generic" so it is not 100% confirmed to be virus or malware, it just warns you that this "may" be the virus/malware.
